const shopTypes = {
    UPDATE_COLLECTION: "UPDATE_COLLECTION",
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_ERROR: 'FETCH_COLLECTION_ERROR',
}

export default shopTypes
