export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN'
export const ADD_ITEM = 'ADD_ITEM'
export const INCREASE_QTY = 'INCREASE_QTY'
export const DECREASE_QTY = 'DECREASE_QTY'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'


